/* Recetario completo · Departamento de Cocina · Residencia SAET
   Extraído de https://sites.google.com/view/residencia-saet/cocina/recetas */
const RECETAS_FULL = {
"🥩 Vacuno": [
 {name:"Bistec",ingredients:["50 porciones de bistec de posta","3 cabezas de ajo","1 cucharada de ají color","1 cucharada de mostaza","1/2 taza de salsa de soya","Aceite (opcional, para sellar)","Sal"],steps:["Preparar el adobo: mezclar en un bol los ajos triturados, mostaza, salsa de soya, sal y orégano hasta formar una pasta homogénea.","Untar cada bistec por ambos lados con la mezcla.","En una sartén con muy poco aceite, sellar los bistecs por ambos lados (1 minuto por lado) y reservar.","En la base de las bandejas de horno, esparcir una mezcla de orégano seco y ají color.","Acomodar los bistecs sobre esa cama de especias y hornear a 160 °C por 1 hora."]},
 {name:"Carne al jugo",ingredients:["10 kg de carne (abastero, asado carnicero, asiento)","8 cebollas","4 pimentones","8 zanahorias","2 cabezas de ajo","2 L de vino tinto","Aceite y sal"],steps:["Usar 2 ollas distribuyendo los ingredientes por igual.","En una olla, sellar la carne por todos sus lados con aceite a fuego fuerte.","Picar zanahorias y pimentones en trozos; cebollas en trozos.","Incorporar cebolla, pimentón, zanahoria y ajo picado con sal. Saltear hasta que la cebolla esté translúcida.","Verter el vino, tapar y cocinar a fuego bajo unas 2 horas.","Retirar la carne y trozarla.","Moler todas las verduras de la olla con minipimer. Si queda muy líquido, espesar con maicena o harina disuelta en agua.","Revolver, rectificar sazón y servir."]},
 {name:"Cazuela de vacuno",ingredients:["7 kg de carne (sobrecostilla, posta paleta, asiento o abastero)","7 kg de papas","5 kg de zapallo","1/2 kg de arroz","2 kg de porotos verdes","4 kg de choclo en trozo congelado","3 cebollas grandes","2 pimentones rojos","4 zanahorias","2 paquetes de cilantro","1 cabeza de ajo","1 ramita de apio","Sal y orégano"],steps:["Cortar la carne en trozos.","Preparar un sofrito con ajo picado fino, rama de apio, tallos de cilantro atados, zanahoria en rodajas, cebolla en brunoise, sal y orégano.","Pelar papas, cocer en agua salada 15-30 minutos. Reservar.","Trozar zapallo, cocer en agua salada 10-15 minutos. Reservar.","Agregar carne al sofrito, llenar con agua hasta 3/4 y hervir 30 minutos a 1 hora según el corte.","Retirar tallos de cilantro y apio.","Agregar choclo y arroz, dejar 10-15 minutos.","Agregar porotos verdes 10-20 minutos antes de servir."]},
 {name:"Chapsui de vacuno",ingredients:["6 kg de abastero","6 brócolis","12 zanahorias","6 paquetes de cebollín","10 zapallos italianos","4 pimentones","1/2 L de salsa de soya","50 g de orégano","Aceite y sal"],steps:["Mezclar 1 taza de salsa de soja y 1 taza de agua para el salteo de verduras.","Saltear la carne en tiritas a fuego fuerte con sal hasta dorar. Reservar.","Cortar pimentón, zapallo italiano y zanahorias en juliana; brócoli en ramas pequeñas.","Saltear cada verdura por separado con la mezcla de soja hasta dejarlas al dente.","Preparar salsa: 1 taza de agua, 2 tazas de soja y 2 cucharadas de maicena.","Unir verduras y carne, saltear 5 minutos, agregar la salsa y remover bien."]},
 {name:"Charquicán",ingredients:["6 kg de zapallo","9 kg de papas","3 kg de choclo en grano congelado","3 kg de carne molida","5 cebollas grandes","3 pimentones rojos","1 cabeza de ajo","100 g de ají color","50 huevos","1/2 L de vino blanco","1 paquete de cilantro","Aceite, comino y sal"],steps:["Cocer papas y zapallo en cubos en agua con sal hasta blandos. Escurrir y moler levemente (puré con trozos).","Hacer sofrito con zanahoria, cebolla, ajo y pimentón en brunoise hasta que la cebolla esté translúcida; agregar sal y vino blanco y cocinar 5 minutos.","Sofreír la carne molida con ají de color, sal y comino.","Cocer el choclo según el envase.","Freír los huevos.","Mezclar papas, zapallo, choclo, carne y sofrito. Servir con un huevo frito y cilantro picado."]},
 {name:"Lomo saltado",ingredients:["5 kg de huachalomo (u otra carne de vacuno)","6 cebollas moradas","3 kg de tomate","2 paquetes de cilantro","3 paquetes de cebollín","5 pimentones","1 cabeza de ajo","500 ml de salsa de soya","500 ml de vino tinto o vinagre","3 cucharadas de maicena","Aceite, sal, ají color, orégano"],steps:["Cortar la carne en tiras y sazonar ligeramente (la soya aporta sal).","Cortar verduras en gajos/bastones; cilantro picado fino.","Sellar la carne en aceite caliente. Agregar aliños y vino, luego vinagre. Reservar.","Cocinar los vegetales al dente, agregar la carne y salsa de soya, dejar 5 minutos. El tomate al final.","Apagar el fuego, agregar el cilantro y servir con arroz blanco y papas fritas."]}
],
"🐟 Pescado": [
 {name:"Croquetas de jurel",ingredients:["15 tarros de jurel","20 huevos","1 kg de harina de avena","3 cebollas grandes","3 pimentones rojos","5 zanahorias","1 cabeza de ajo","50 g de orégano","4 L de aceite","Sal"],steps:["Hacer un sofrito con cebollas, pimentones, zanahorias, ajo y orégano.","En un bowl, mezclar el jurel desmenuzado, el sofrito, los huevos, la avena molida, sal y pimienta.","Formar croquetas (~95 g) y freír en abundante aceite caliente por ambos lados."]},
 {name:"Pescado frito",ingredients:["50 porciones de pescado (reineta, merluza)","250 g de harina","250 g de maicena","30 huevos","4 L de aceite","1 L de agua con gas","1 cabeza de ajo","4 kg de limón","1 paquete de cilantro","Sal y orégano"],steps:["Limpiar y aliñar el pescado con jugo de limón, ajo, sal y orégano. Reservar refrigerado.","Batir huevos, agregar agua con gas, luego harina y maicena hasta el punto deseado. Agregar condimentos, ajo y cilantro picado.","Freír en abundante aceite por ambos lados y escurrir. Considerar 1h30 para 50 porciones.","Reservar en horno a 150 °C; el pescado debe alcanzar 65 °C interior."]}
],
"🦃 Pavo": [
 {name:"Pavo a la manzana",ingredients:["Pechuga de pavo deshuesada para 50 porciones","4 kg de manzana verde","6 cebollas grandes","1 L de vino blanco","1 L de aceite de oliva","50 g de miel","100 g de romero","Sal"],steps:["Sofreír cebolla y zanahoria en brunoise con ajo rallado hasta dorar.","Sazonar el pavo y agregar al sofrito. Dorar, añadir romero, orégano y vino; cocinar a fuego bajo 10 minutos.","Agregar la miel y cocinar 30 minutos más a fuego bajo, revolviendo.","Agregar las manzanas en cubos y cocinar hasta que estén listas."]},
 {name:"Pavo a la mostaza",ingredients:["Pavo sin hueso y pechuga deshuesada para 50 porciones","2 kg de mostaza","4 cucharadas de miel","2 cabezas de ajo","Aceite"],steps:["Trozar el pavo en medallones.","Mezclar mostaza, miel y ajo machacado.","Macerar los medallones al menos media hora.","Precalentar el horno a 180 °C. Disponer el pavo con el macerado.","Hornear 30 minutos hasta 74 °C interior."]}
],
"🍗 Pollo": [
 {name:"Cazuela de pollo",ingredients:["50 trutros de pollo","7 kg de papas","5 kg de zapallo","1/2 kg de arroz","2 kg de porotos verdes","4 kg de choclo congelado en trozo","3 cebollas grandes","4 zanahorias","2 paquetes de cilantro","2 pimentones rojos","1 cabeza de ajo","1 ramita de apio","Orégano y sal"],steps:["Hacer sofrito con ajo, apio, tallos de cilantro atados, zanahoria en rodajas y cebolla en brunoise; sal y orégano.","Cocer papas en agua con sal 15-30 minutos. Reservar.","Cocer zapallo trozado 10-15 minutos. Reservar.","Agregar los trutros al sofrito, llenar con agua hasta 3/4 y hervir 30 minutos.","Retirar cilantro y apio. Agregar choclo, poroto verde y arroz; cocinar 10-15 minutos. Servir."]},
 {name:"Estofado de pollo",ingredients:["8 kg de pechugas de pollo","6 kg de papas","2 kg de zanahoria","1 kg de tomate","6 cebollas grandes","5 pimentones","1 cabeza de ajo","1 paquete de laurel","Aceite y sal"],steps:["Usar 2 ollas, repartiendo los ingredientes.","Sellar el pollo hasta dorar.","Agregar cebolla, pimentón y ajo; sofreír.","Agregar papas, zanahoria, sal, orégano y ají color. Cubrir con agua y hervir 20 minutos.","Agregar salsa de tomate y hervir 20 minutos más. Rectificar sal y servir."]},
 {name:"Pollo a la mostaza",ingredients:["50 porciones de trutros con piel","3 cabezas de ajo","4 cucharadas de miel","3 kg de mostaza","Sal y orégano","Opcional: 500 ml de vino blanco"],steps:["Verificar que el pollo esté descongelado.","Combinar mostaza, ajo machacado, miel, orégano y sal (y vino si se desea).","Adobar el pollo y macerar al menos 1 hora.","Hornear a 180 °C por 1h30 hasta 74 °C interior. Servir."]},
 {name:"Pollo asado",ingredients:["50 porciones de trutros con piel","8 cebollas","2 cabezas de ajo","3 kg de limón","Orégano y sal"],steps:["Verificar que el pollo esté descongelado.","Combinar jugo de limón con ajo prensado, orégano y sal. Adobar y macerar 1 hora.","Cortar cebollas en pluma y formar una cama en las bandejas; colocar el pollo encima.","Hornear a 180 °C por 1h30 hasta 74 °C interior. Servir."]}
],
"🐖 Cerdo": [
 {name:"Chuleta o plateada de cerdo al jugo",ingredients:["50 chuletas vetadas o plateada de cerdo","6 cebollas grandes","2 kg de zanahoria","2 cabezas de ajo","1 paquete de laurel","1 L de vino blanco","Ají color, aceite y sal"],steps:["Condimentar con ajo rallado y vino blanco (sin sal aún). Reposar mínimo 30 minutos.","Cortar zanahoria en rodajas, cebolla en pluma, pimentón en juliana.","Sofreír esas verduras con laurel y sal; al volverse translúcida la cebolla, agregar 1 L de agua y hervir.","Bajar a fuego mínimo.","Sellar las chuletas en sartén y transferirlas a la olla.","Cocinar a fuego bajo 20-30 minutos (la plateada requiere más). Interior seguro del cerdo: 63 °C."]},
 {name:"Chuleta escabechada",ingredients:["50 porciones de chuletas de cerdo","1 L de vinagre de vino blanco (o de manzana)","2 cabezas de ajo","6 pimentones","6 cebollas grandes","Orégano, sal y pimienta","Aceite","1 L de agua","Azúcar (opcional)"],steps:["Sazonar y sellar las chuletas hasta dorar; reservar.","Sudar cebolla en pluma, pimentón en juliana y ajo rallado 5 minutos con orégano, sal y pimienta.","Verter el vinagre y 1 L de agua; hervir 2 minutos.","Agregar las chuletas y cocinar 20 minutos a fuego bajo (interior 63 °C).","Opcional: una pizca de azúcar para equilibrar."]}
],
"🍝 Pastas": [
 {name:"Espagueti Pomodoro",ingredients:["5 kg de espagueti n°77","8 kg de tomates","8 paquetes de queso rallado (40 g)","1 kg de zanahoria","2 cabezas de ajo","8 paquetes de salsa de tomate","6 cebollas grandes","Laurel, orégano, sal, aceite","3 kg de carne molida (para boloñesa)"],steps:["Cocer los espaguetis al dente; escurrir y agregar un poco de aceite.","Pomodoro: cortar tomates en cubos. Sofreír cebolla y zanahoria hasta transparencia, agregar tomate y cocinar 1h30. Sazonar.","Boloñesa (opcional): sofreír carne molida con orégano y sal; añadir salsa de tomate. Servir."]},
 {name:"Fettuccini Alfredo",ingredients:["4 kg de fettuccini","3 L de leche","2 L de crema","500 g de mantequilla","200 g de queso parmesano","1,5 kg de jamón","500 g de harina","Nuez moscada y sal"],steps:["Cocer los fettuccini al dente; escurrir y agregar un chorrito de aceite.","Derretir la mantequilla con nuez moscada y sal.","Integrar crema y leche.","Agregar el queso, bajar el fuego y cocinar 5 minutos.","Incorporar jamón picado. Servir."]},
 {name:"Lasagna Bolognesa",ingredients:["6 paquetes de lasaña precocida (400 g)","4 kg de carne molida","7 kg de tomate","10 cebollas","1 kg de zanahoria","10 sobres de queso rallado","50 láminas de queso","5 L de leche","1 L de crema","500 g de mantequilla","500 g de harina","Nuez moscada","200 g de ketchup (o 1 cda de azúcar)","Aceite y sal"],steps:["Boloñesa: sofreír cebolla y zanahoria, agregar tomate en cubos y cocinar 1h30; sofreír carne aparte y unir con la salsa.","Bechamel: derretir mantequilla, agregar harina, verter leche fría y batir; nuez moscada y pimienta; apagar al primer hervor.","Montar capas de salsas y pasta; terminar con queso rallado y hornear hasta dorar."]},
 {name:"Lasagna de Verdura",ingredients:["6 paquetes de lasaña precocida (400 g)","5 L de leche","1 L de crema","5 sobres de queso rallado (80 g)","250 g de mantequilla","500 g de harina","9 kg de tomate","1 kg de zanahoria","50 láminas de queso","10 zapallos italianos","10 berenjenas","8 cebollas grandes","1 cabeza de ajo","2 cdas de azúcar o 200 g de ketchup","Nuez moscada, laurel, sal y aceite"],steps:["Pomodoro: sofreír cebolla, tomate y zanahoria con laurel, sal y azúcar; procesar con minipimer.","Bechamel: derretir mantequilla, agregar harina, verter leche fría, nuez moscada y pimienta; al primer hervor incorporar crema.","Cortar zapallos y berenjenas en láminas con sal y aceite.","Armar capas: pomodoro, lasaña, verduras y bechamel; terminar con queso. Hornear a 180 °C por 25 minutos."]}
],
"🥘 Guisos": [
 {name:"Lentejas con longaniza",ingredients:["4 kg de lentejas","3 kg de zapallo","1 kg de zanahoria","6 cebollas grandes","1 kg de arroz","4 kg de longanizas","5 hojas de laurel","Aceite y sal"],steps:["Remojar las lentejas según el envase.","Sofreír zanahoria y cebolla en brunoise; sazonar.","Agregar lentejas y laurel; cubrir con agua y hervir.","Agregar zapallo en cubos y cocinar ~30 minutos a fuego bajo.","Hervir las longanizas 5 minutos, luego hornear a 180 °C hasta dorar. Servir."]},
 {name:"Pastel de papas",ingredients:["4 kg de carne molida","6 cebollas grandes","6 pimentones","2 kg de aceitunas","30 huevos","12 kg de papas","2 L de leche","250 g de mantequilla","5 sobres de queso rallado","1 cabeza de ajo","Aceite y sal"],steps:["Pino: sofreír cebolla, pimentón y ajo hasta transparencia; agregar la carne y condimentar.","Hervir huevos 10-12 minutos, pelar y cortar en gajos.","Puré: con papas, leche y mantequilla.","Montar: pino, huevos y aceitunas, cubrir con puré, espolvorear queso y hornear a 200 °C hasta dorar."]},
 {name:"Porotos con rienda",ingredients:["4 kg de porotos","3 paquetes de tallarines (400 g)","2 kg de zapallo","1 kg de zanahoria","6 cebollas","2 pimentones rojos","2 cabezas de ajo","4 kg de longanizas","Laurel, orégano, sal y aceite"],steps:["Remojar los porotos la noche anterior.","Cocer los porotos en agua fría con sal y laurel hasta hervir (~20 minutos).","Agregar zapallo en cubos; cocinar 10-15 minutos.","Añadir tallarines y cocinar 8 minutos.","Hacer un sofrito (cebolla, pimentón, zanahoria, ajo, orégano, sal) e incorporarlo.","Hervir longanizas 5 minutos, trozar y agregar. Servir semilíquido."]},
 {name:"Porotos granados con mazamorra",ingredients:["6 kg de porotos granados desgranados","3 kg de zapallo","6 kg de choclo desgranado","3 cebollas grandes","2 pimentones rojos","1 cabeza de ajo","1 paquete de albahaca","100 g de ají color","Aceite y sal"],steps:["Repartir en dos ollas.","Cocer los porotos en agua fría con sal y albahaca hasta hervir (~20 minutos).","Agregar zapallo en cubos y choclo triturado; cocinar 10-20 minutos.","Hacer sofrito de cebolla, pimentón y ajo con albahaca, ají color y sal; incorporar.","Color: freír ajo en aceite, retirarlo y agregar ají color revolviendo."]},
 {name:"Zapallo italiano relleno",ingredients:["35 zapallos italianos grandes","3 kg de posta molida","6 cebollas grandes","1 kg de zanahoria","3 pimentones rojos","1 cabeza de ajo","70 láminas de queso","Orégano y sal"],steps:["Hervir los zapallos 5-7 minutos al dente.","Cortar por la mitad y ahuecar; moler la pulpa y reservar.","Picar cebolla, pimentón y zanahoria en brunoise.","Hacer un pino con la carne y verduras + ajo; incorporar la pulpa y sazonar.","Rellenar cada mitad y poner una lámina de queso.","Hornear a 200 °C hasta gratinar."]},
 {name:"Porotos con Mazamorra",ingredients:["6 kg de porotos granados desgranados","3 kg de zapallo amarillo","6 kg de choclo en grano","2 cebollas grandes","1 pimentón rojo","1 cabeza de ajo","1 paquete de albahaca","100 g de ají color"],steps:["Repartir en dos ollas.","Cocer porotos en agua fría con sal y albahaca hasta hervir (~10 minutos).","Agregar zapallo en cubos cuando rompa el hervor.","Cocinar 20 minutos a fuego bajo.","Sofreír cebolla y pimentón.","Moler el choclo con agua y albahaca (mazamorra).","Color: aceite, ajo y ají color a fuego muy bajo 5 minutos.","Agregar sofrito y mazamorra; cocinar hasta que quede espeso."]}
],
"🍚 Acompañamientos": [
 {name:"Arroz blanco",ingredients:["4 kg de arroz","2 dientes de ajo","Sal, aceite y agua"],steps:["Dividir en dos ollas.","Lavar el arroz hasta que el agua salga casi transparente.","Sofreír el ajo en aceite sin dorar.","Agregar agua hirviendo en igual cantidad que el arroz; subir el fuego.","Agregar sal (2 cucharaditas).","Al hervir, incorporar el arroz, revolver y esperar nuevo hervor.","Tapar, fuego mínimo, cocinar 18 minutos.","Reposar y revolver para separar los granos."]},
 {name:"Arroz chaufán",ingredients:["4 kg de arroz","500 g de jamón","12 huevos"],steps:["Preparar el arroz como el blanco.","Hacer tortillas de huevo y picarlas en cuadritos.","Cortar y sofreír el jamón.","Incorporar jamón y tortilla al arroz. Mezclar y servir."]},
 {name:"Arroz primavera",ingredients:["Poroto verde picado","Choclo desgranado","Arvejas","Zanahoria picada"],steps:["Preparar el arroz como el blanco.","Al servir, incorporar la verdura surtida previamente cocida."]},
 {name:"Papas al horno",ingredients:["12 kg de papas","Aceite de oliva","2 paquetes de perejil","Sal"],steps:["Lavar, pelar y cortar las papas en gajos.","Picar el perejil fino.","Marinar las papas en aceite, sal y perejil.","Precalentar el horno a 160 °C.","Disponer en bandejas sin sobreponer.","Hornear 20 minutos, dar vuelta y 15-20 minutos más hasta dorar. Servir."]},
 {name:"Papas cocidas",ingredients:["12 kg de papas","Sal"],steps:["Lavar y pelar las papas.","Cocer en agua fría con sal a fuego medio.","Hervir hasta que estén blandas al centro, sin pasarse."]},
 {name:"Papas fritas",ingredients:["9 kg de papas prefritas","4 L de aceite"],steps:["Freír las papas prefritas en abundante aceite caliente hasta dorar."]},
 {name:"Papas mayo",ingredients:["12 kg de papas","1 kg de zanahorias","2 kg de mayonesa","Sal"],steps:["Cocer papas y zanahorias sin pelar en agua fría con sal.","Al hervir, verificar que estén blandas sin pasarse.","Escurrir, enfriar y pelar.","Cortar papas en cubos y zanahorias en brunoise.","Agregar la mayonesa y mezclar con cuidado."]},
 {name:"Pastelera de choclo",ingredients:["Opción 1: 11 kg de pastelera congelada","Opción 2: 11 kg de choclo desgranado congelado + 1 paquete de albahaca + aceite y sal","Opción 3 (casera): 40-45 choclos enteros + 6 cebollas + albahaca + aceite y sal"],steps:["Si es congelada, seguir el empaque.","Si es choclo desgranado, triturar con albahaca.","Casera: sudar cebolla en brunoise con aceite y sal.","Desgranar y triturar los choclos con albahaca.","Agregar a la olla y cocinar a fuego medio-bajo ~30 minutos revolviendo.","Rectificar sazón y servir."]},
 {name:"Polenta",ingredients:["3 kg de polenta","250 g de mantequilla","2 L de leche","2 L de crema","12 paquetes de queso rallado (40 g)"],steps:["Medir la polenta en tazas.","Por cada taza de polenta: 2 de agua, 1 de leche, 1 de crema; llevar a ebullición.","Bajar el fuego y agregar la polenta en lluvia revolviendo 20-25 minutos.","Apagar, agregar la mantequilla y disolver.","Incorporar el queso y servir de inmediato."]},
 {name:"Puré de papas natural",ingredients:["12 kg de papas","2 L de leche","250 g de mantequilla","Sal","Opcional: nuez moscada"],steps:["Cortar las papas en cubos.","Cocer en agua fría con sal hasta blandas.","Escurrir, reservar una taza del agua de cocción.","Calentar la leche (con nuez moscada opcional).","Moler las papas, agregar mantequilla y leche tibia; revolver.","Ajustar con agua de cocción si falta cremosidad. Rectificar sal."]},
 {name:"Puré verde de papas",ingredients:["12 kg de papas","2 L de leche","250 g de mantequilla","3 atados de perejil","Sal"],steps:["Cortar las papas en cubos y cocer en agua con sal hasta blandas.","Escurrir y reservar una taza del agua de cocción.","Licuar hojas de perejil con mantequilla derretida, nuez moscada y leche.","Moler las papas y agregar la mezcla verde; revolver.","Ajustar con agua de cocción si falta cremosidad. Rectificar sal."]}
],
"🍰 Dulces": [
 {name:"Rollos de canela",ingredients:["1.250 ml de leche tibia","500 g de azúcar","35 g de levadura seca","1 cdita de sal","2.600 g de harina","10 huevos","5 cditas de vainilla","350 g de mantequilla sin sal","250 g de azúcar granulada + 250 g de azúcar rubia (relleno)","30 g de canela molida","400 g de mantequilla (enrollado)","600 g de queso crema","500 g de mantequilla y 1.100 g de azúcar flor (frosting)"],steps:["Fermento: combinar y dejar que triplique su volumen.","Entibiar la leche con levadura y azúcar; reposar 10 minutos. Integrar mantequilla y huevos, luego la harina por tandas.","Amasar 10 minutos y reposar 1-2 horas hasta duplicar.","Relleno: mezclar azúcar y canela.","Estirar la masa, untar mantequilla y distribuir la canela; enrollar.","Cortar en trozos de ~3 cm, reposar 30-40 minutos y hornear a 160 °C por ~12 minutos."]},
 {name:"Brazo de reina",ingredients:["18 huevos","720 g de azúcar","460 g de harina","260 g de maicena","Pizca de sal","2 kg de manjar","400 cc de crema fría","150 g de nueces (opcional)"],steps:["Batir las claras con sal y agregar el azúcar hasta picos firmes.","Añadir las yemas una a una.","Incorporar harina y maicena cernidas en forma envolvente.","Esparcir en bandejas con papel mantequilla y hornear 10 minutos a 180 °C.","Despegar y enrollar; enfriar.","Relleno: batir la crema, agregar el manjar.","Rellenar, envolver en film y refrigerar; decorar con manjar y nueces."]},
 {name:"Kuchen de plátano",ingredients:["1.400 g de harina","800 g de mantequilla","400 g de azúcar (masa)","420 g de azúcar (caramelo)","168 g de mantequilla (caramelo)","268 g de crema","1½ cdita de sal","15 plátanos en rodajas"],steps:["Masa: mezclar con las yemas de los dedos hasta formar masa; estirar en el molde, pinchar y congelar 15 minutos; hornear a 180 °C por 13 minutos.","Caramelo salado: hacer caramelo ámbar, agregar la mantequilla y batir; incorporar la crema y la sal; refrigerar.","Untar caramelo sobre la base, distribuir el plátano y cubrir con más caramelo. Cortar y enfriar."]},
 {name:"Galletas de manzana, canela y nuez",ingredients:["908 g de mantequilla","800 g de chancaca","360 g de azúcar","240 g de huevos","1.932 g de harina","16 g de sal","12 g de maicena","12 g de bicarbonato","1.120 g de manzana en cubos (asada)","600 g de nueces","16 g de canela","Relleno: 800 g de manzana, 220 g de azúcar rubia, 160 ml de agua, 16 g de maicena, 28 g de jugo de limón, 16 g de canela","Caramelo salado: 200 g de azúcar, 160 g de mantequilla, 110 g de crema, 3 g de sal"],steps:["Cremar mantequilla con azúcar y chancaca 3 minutos.","Incorporar los huevos.","Agregar los secos cernidos, luego los cubos de manzana y las nueces.","Porcionar esferas de 140 g y hornear a 200 °C ~10 minutos.","En caliente, crear un hueco al centro y redondear bordes; enfriar.","Relleno de manzana: cocinar manzana con azúcar, canela y limón; espesar con maicena.","Caramelo salado: caramelo ámbar + mantequilla + crema + sal; refrigerar.","Decorar las galletas con el relleno y el caramelo."]},
 {name:"Panqueques",ingredients:["2,5 L de leche","5 cdas de vainilla","1.250 g de harina","15 huevos","Aceite","2 kg de manjar"],steps:["Batir todos los ingredientes de la masa hasta integrar.","Cocinar cada panqueque 2-3 minutos en la panquequera.","Rellenar con manjar; opcional azúcar flor para presentar."]},
 {name:"Pie de limón",ingredients:["1.400 g de harina","960 g de margarina","480 g de azúcar","1 huevo","Ralladura de 10 limones","Vainilla","6 tarros de leche condensada","1½ L de jugo de limón colado (~20 limones)","12 claras (~400 g)","400 ml de agua y 800 g de azúcar (merengue)"],steps:["Masa: mezclar con las yemas de los dedos, estirar en el molde, pinchar, congelar 15 minutos y hornear a 180 °C por 13 minutos.","Relleno: batir leche condensada con jugo de limón y yemas; verter sobre las bases y hornear 5 minutos; enfriar.","Merengue italiano: almíbar a 117 °C vertido sobre claras a nieve batiendo a máxima velocidad; decorar y tostar. 10 porciones por molde."]},
 {name:"Sémola con leche",ingredients:["5 L de leche","500 g de sémola","250 g de azúcar","2 cdas de canela molida","2 cdas de vainilla","Ralladura de naranja","Opcional: anís estrellado, clavo de olor","250 g de azúcar (caramelo)"],steps:["Caramelo: azúcar con agua hasta ámbar; agregar agua hirviendo; verter en el molde y enfriar.","Calentar la leche con azúcar, canela, ralladura y aromáticos hasta hervir.","Cocinar a fuego lento 5 minutos y colar.","Agregar la sémola en lluvia revolviendo 8-10 minutos.","Verter en el molde con caramelo y refrigerar hasta cuajar."]}
],
"🥪 Salados": [
 {name:"Completos",ingredients:["80 panes de completo","20 paltas","20 tomates","80 vienesas","Lactonesa: 150 ml de leche, 300 ml de aceite, sal","Salsa verde: cebolla, cilantro, ají verde, limón, aceite, sal"],steps:["Picar tomate en brunoise con sal.","Triturar la palta con sal.","Calentar los panes a 150 °C 15 minutos antes de servir.","Cocer las vienesas a fuego lento.","Lactonesa: leche, sal y condimentos con minipimer, agregando aceite hasta consistencia.","Salsa verde: picar cebolla, cilantro y ají; mezclar con limón, aceite y sal."]},
 {name:"Crepes de espinaca",ingredients:["Crêpes: 4 L de leche, 500 g de espinaca, 1 kg de harina, sal y aceite","Relleno: 3 kg de pechuga de pollo, 1 kg de limones, 3 L de leche, 150 g de mantequilla, 150 g de harina, 1,2 kg de queso mantecoso, sal, nuez moscada y pimienta","Opcional: 2 kg de choclo, 3 pimentones o 4 cebollas"],steps:["Cortar el pollo en cubitos y macerar en limón y sal 2 horas.","Saltear el pollo con los acompañamientos opcionales.","Crêpes: licuar todos los ingredientes y cocinar en sartén antiadherente.","Bechamel: mantequilla + harina + leche fría; nuez moscada y pimienta; apagar al primer hervor.","Rellenar los crêpes con pollo y queso, formar cilindros y hornear 10 minutos a 180 °C.","Servir con bechamel."]},
 {name:"Empanada de pino",ingredients:["Masa: 5 kg de harina, 5 cditas de sal, 5 huevos, 500 cc de vino blanco, 650 g de manteca, 1.600 ml de agua hirviendo","Pino: 3 kg de carne picada, 600 ml de aceite, 6 kg de cebolla, orégano, ají color, perejil, sal, azúcar, maicena","1 kg de aceitunas, 500 g de pasas, 24 huevos"],steps:["Masa: mezclar (menos el agua), agregar agua hasta integrar, amasar 5 minutos; estirar a 5 mm y cortar discos.","Pino: sellar carne con aliños, agregar cebolla hasta cristalizar, azúcar y perejil; espesar con maicena y enfriar.","Hervir huevos y cuartear; armar empanadas, pincelar con yema y hornear a 180 °C por 35-40 minutos."]},
 {name:"Ensalada César",ingredients:["6 lechugas costinas","1 kg de pan en cubos","6 kg de pechuga de pollo","1,2 kg de queso","3 botellas de aderezo César","Aderezo casero: 24 yogur griego, 12 cdas de mayonesa, 6 cdas de mostaza, sal y pimienta"],steps:["Macerar el pollo en cubitos (sal, pimienta, limón, ajo, ají color) 3 horas.","Saltear el pollo, enfriar y reservar.","Lavar y cortar la lechuga; desinfectar y refrigerar.","Crutones: pan en cubos con aceite, orégano y sal al horno 10-12 minutos.","Rallar el queso.","Mezclar lechuga, pollo, queso y aderezo al momento de servir."]},
 {name:"Ensalada coleslaw",ingredients:["1/2 repollo morado","1/2 repollo blanco","3 zanahorias","300 g de mayonesa","300 g de mostaza","100 ml de vinagre de manzana","3 cdas de miel","3 limones","Sal"],steps:["Rallar repollos y zanahoria (~3 kg).","Mezclar mayonesa, mostaza, miel, vinagre y limón con sal.","Mezclar todo y servir."]},
 {name:"Ensalada pico de gallo",ingredients:["20 tomates","4 cebollas","Pimentón verde o rojo","2 paquetes de cilantro","Limón, aceite y sal","Opcional: ají verde"],steps:["Picar tomate, cebolla y pimentón en brunoise; cilantro fino.","Proporción: 2 de tomate, 1 de cebolla, 1 de cilantro.","Amortiguar la cebolla en agua hirviendo y escurrir.","Mezclar todo con limón, sal y aceite. Servir."]},
 {name:"Hamburguesa",ingredients:["8 kg de carne de vacuno","5 paquetes de tocino ahumado (180 g)","1 cebolla grande","70 panes de hamburguesa","70 láminas de queso","Aceite y sal"],steps:["Limpiar la carne.","Triturar cebolla y tocino y mezclar con la carne; sal.","Pesar 110-120 g por hamburguesa y freír con una gota de aceite.","Sugerencia: acompañar con coleslaw."]},
 {name:"Omelette",ingredients:["80 huevos","40 láminas de queso","10 cebollas","10 longanizas","6 pimentones","Aceite y sal"],steps:["Caramelizar la cebolla en pluma a fuego bajo.","Saltear pimentón en juliana y las longanizas en rodajas.","Mezclar cebolla, pimentón y longaniza para el relleno.","Batir 2 huevos con sal y orégano; cocinar en sartén.","A medio cocer, agregar relleno y una lámina de queso; doblar y cocinar 1 minuto más."]},
 {name:"Pizza",ingredients:["Masa: 5 kg de harina, 6½ tazas de agua fría, 6½ de agua caliente, 6½ cdas de levadura, 6½ cditas de azúcar, 20 cdas de aceite de oliva, 5 cditas de sal","Topping: 10 paquetes de salsa de tomate, 3,4 kg de queso mantecoso, 600 g de pepperoni"],steps:["Unir aguas, levadura y azúcar; reposar.","Mezclar harina y aceite, hacer un hoyo y poner la sal alrededor.","Agregar la levadura cuando burbujee y amasar hasta que no se pegue.","Dividir en 4 y reposar en bolsas con aceite.","Dejar leudar la mañana para usar en la tarde."]},
 {name:"Pollo asado con verduras salteadas",ingredients:["40 trutros enteros o 60 mitades","3 brócolis","3 coliflores","5 zanahorias","6 morrones","6 cebollas","6 cebollines","8 zapallos italianos","1 cabeza de ajo","Limón, aceite y sal"],steps:["Macerar el pollo con sal, ajo, limón y especias.","Hornear a 180 °C por 1 hora.","Saltear las verduras por separado.","Combinar las verduras al final."]},
 {name:"Sándwich de ave pimentón",ingredients:["40 panes","20 paltas","4 kg de pechuga de pollo","4 pimentones rojos","1 kg de mayonesa","2 hojas de laurel","Sal y pimienta"],steps:["Hervir el pollo con 2 pimentones, laurel y sal 20 minutos (73 °C).","Reservar el caldo.","Asar los 2 pimentones restantes, pelar.","Procesar pollo y pimentones.","Mezclar con mayonesa hasta cremoso; sal y pimienta.","Reposar 30 minutos antes de servir."]},
 {name:"Shawarma de Falafel",ingredients:["3 kg de garbanzos (remojados)","3 paquetes de perejil","3 cebollas","1/2 taza de aceite de oliva","40 g de comino, 40 g de sal, 40 g de bicarbonato","4 L de aceite (freír)","Salsa: 450 g de tahini, 6 yogures, 1 taza de mayonesa, 1½ taza de limón, especias, ajo","Ensalada: 3 kg de tomate, 3 pepinos, 4 lechugas, 3 cebollas moradas, 3 paquetes de perejil","60 panes árabes"],steps:["Remojar los garbanzos desde el día anterior.","Triturar garbanzos con cebolla, ajo y perejil.","Agregar sal, bicarbonato, aceite y comino.","Freír el falafel a 170 °C hasta dorar.","Salsa árabe: batir tahini, yogur, mayonesa, limón, especias y ajo.","Ensalada: tomate sin semilla, pepino, lechuga y cebolla morada con aceite y sal."]},
 {name:"Shawarma Mixto",ingredients:["Pan árabe: 3 kg de harina, aguas, levadura, azúcar, aceite de oliva, sal","3 kg de vacuno y 4 kg de pollo","8 yogures","Tzatziki: pepino, menta, ajo, limón","Ensaladas: tomate, lechuga, perejil","Especias: canela, comino, pimientas, clavo"],steps:["Pan árabe: levar, amasar, dividir y cocinar en sartén 1-2 minutos por lado.","Macerar el pollo con yogur, especias y sal; saltear.","Macerar el vacuno con especias y sal; saltear.","Tzatziki: yogur, pepino rallado y escurrido, aceite, limón, menta, sal y ajo.","Cortar las ensaladas y armar."]},
 {name:"Sopaipillas",ingredients:["5,4 kg de harina","6 cdas de sal","10 cdas de polvo de hornear","500 g de manteca","2,5 kg de zapallo","3 L de aceite","Chancaca (para pasadas): 3 paquetes (400 g), naranja, clavo y canela"],steps:["Cocer el zapallo en agua con sal ~15 minutos; escurrir reservando 500 ml.","Moler el zapallo y agregar harina hasta integrar; reposar 30 minutos.","Estirar a 1/2 cm, pinchar, cortar y freír a 170 °C.","Pasadas: hervir chancaca con especias y agua, sumergir las sopaipillas 20 minutos."]},
 {name:"Tacos",ingredients:["80 tortillas","5 kg de carne de vacuno (o pollo)","8 cebollas","6 pimentones rojos","2 lechugas","3 zanahorias","4 kg de choclo congelado","Salsa verde: cebolla, cilantro, ají verde, limón","Sal y aceite"],steps:["Pollo: descongelar, cortar en tiras y macerar en limón y sal 2 horas; saltear.","Vacuno: cortar en tiras y saltear con sal a fuego fuerte.","Cocer el choclo según el envase.","Sofreír cebolla, pimentón y zanahoria; mezclar con la carne.","Salsa verde: cebolla, cilantro y ají con limón, sal y aceite."]},
 {name:"Torta de verduras",ingredients:["40 tortillas de taco","4 kg de choclo","3 lechugas","2 kg de atún","4 cebollas","1 kg de mayonesa","15 huevos","1 kg de zanahoria","2 kg de limones","Ciboulette"],steps:["Rallar la zanahoria.","Pasta de huevos: hervir, moler y mezclar con mayonesa.","Atún con cebolla pasada por agua caliente y limón.","Picar la lechuga fina.","Choclo cocido con mayonesa, ciboulette y sal.","Montar capas: mayonesa, tortilla, lechuga, tortilla, atún, tortilla, choclo, tortilla, zanahoria, tortilla, pasta de huevo.","Cortar en 6 porciones por torta."]},
 {name:"Verduras salteadas",ingredients:["4 brócolis","3 coliflores","6 pimentones rojos","6 cebollas","6 cebollines","6 zapallos italianos","5 zanahorias","Sésamo","Aceite y sal"],steps:["Cortar todas las verduras de tamaño similar.","Saltear la cebolla 1 minuto y reservar.","Saltear zanahoria, pimentón, cebollín, coliflor y zapallo 4-6 minutos.","Agregar el brócoli y cocinar 1 minuto.","Sazonar; deben quedar crujientes. Espolvorear sésamo."]}
],
"🍲 Sopas y cremas": [
 {name:"Crema de zapallo",ingredients:["4 kg de zapallo","4 papas medianas","3 cebollas","400 ml de crema de leche sin lactosa","Nuez moscada, orégano y sal"],steps:["Sofreír cebolla, papa, zapallo y orégano con aceite de oliva.","Cubrir con agua y hervir hasta que todo esté blando.","Reservar agua de cocción y licuar las verduras.","Incorporar crema y agua de cocción hasta la consistencia deseada."]},
 {name:"Consomé (ave o vacuno)",ingredients:["2 pechugas de pollo (~800 g)","200 g de cabellitos de ángel (o sémola)","1 morrón","3 huevos","2 cebollas","3 zanahorias","Cilantro, orégano y apio"],steps:["Verificar que el pollo esté descongelado.","Cortar verduras en cubos; atar tallos de cilantro y apio.","Hervir 6 L de agua con pollo, verduras y atado + sal.","Reducir a fuego medio hasta 74 °C interior (30-40 minutos).","Retirar el pollo, agregar los cabellitos y cocinar 10 minutos.","Desmenuzar el pollo e incorporar; agregar huevos 3 minutos más.","Rectificar sal y servir con cilantro."]},
 {name:"Miso Ramen",ingredients:["12 kg de carcasas de pollo","1 kg de patas de pollo (opcional)","5 kg de plateada o similar","500 g de jengibre","4 cabezas de ajo","2 cebollas grandes","40 huevos","5 kg de tallarines n°5","2 kg de pasta de miso","300 ml de aceite de sésamo","200 g de azúcar","1,5 L de salsa de soya","300 g de miel","500 ml de mirin","2 kg de choclo","1,5 kg de brotes de soja","12 cebollines"],steps:["Preparar caldo de pollo con carcasas, jengibre, ajo y cebolla.","Cocinar la carne, los huevos (mollet) y los tallarines.","Integrar la pasta de miso, soya, miel y aceite de sésamo al caldo.","Montar con tallarines, carne, huevo, choclo, brotes y cebollín."]},
 {name:"Pho de vacuno",ingredients:["4 kg de tapapecho","8 kg de hueso carnudo","2 kg de posta rosada","5 kg de tallarines o 2,4 kg de fideos de arroz","3 kg de cebolla","400 g de jengibre","20 anís estrellado","8 canela en rama","Clavo de olor","Cardamomo negro (opcional)","Salsa de pescado","Toppings: cilantro, cebollín, brotes de soja"],steps:["Blanquear huesos y tapapecho 5 minutos; descartar el agua.","Tostar las especias y reservar en gaza.","Tostar cebolla y jengibre al fuego.","Caldo: huesos, carne, cebolla y jengibre en 30 L de agua; hervir y bajar 1 hora; agregar especias y salsa de pescado 2 horas más.","Cortar carnes en láminas; remojar fideos 1 hora.","Pasar fideos por agua hirviendo 15 segundos.","Montar bowl con fideos, carne, cebolla, cebollín y cilantro; agregar caldo muy caliente."]}
],
"🥖 Pan": [
 {name:"Pan Integral",ingredients:["Esponja (x2): 300 g de harina integral, 300 ml de agua tibia, 30 g de levadura","Masa (x2): 65 g de sal, 3 kg de harina integral, 65 g de azúcar, 32 g de levadura, 275 g de linaza, 260 g de miel (opcional), 200 g de mantequilla, 2 L de agua tibia"],steps:["Esponja: mezclar harina, agua y levadura; reposar.","Masa: en batidora, sal, harina, azúcar, levadura, linaza, miel y mantequilla; agregar agua y la esponja; batir 10 minutos.","Formar 10 porciones de 1 kg y 2 de 800 g en moldes.","Reposar tapados hasta duplicar.","Hornear a 160 °C por 25 minutos; rociar agua antes de retirar.","Enfriar, envasar y congelar."]},
 {name:"Pan amasado",ingredients:["5,2 kg de harina","50 g de sal fina","50 g de levadura seca","490 cc de aceite","2,5 L de agua tibia"],steps:["Colocar en la amasadora: agua tibia, aceite, levadura, harina y sal.","Amasar 5 minutos en velocidad 1 hasta bollo homogéneo.","Dividir en porciones de 100 g y formar los panes.","Fermentar hasta doblar el volumen.","Hornear a 160 °C por ~20 minutos."]}
]
};
